### ISSUE TITLE
Opening blog link results in 404

### ISSUE THREAD

**Issue by anshuraj** [30-seconds/30-seconds-blog#2]
## Bug description 

Opening the blog link https://30secondsofcode.org/blog/p/1 results in 404 page not found error.

## Steps to reproduce

Open https://30secondsofcode.org/blog/p/1

## Expected behavior

The page should load the blog post

**Comment by Chalarangelo** [comment]
Hey, there!

As clearly stated in this repository's description, the blog is a work in progress. We are planning to release the blog to the public around February, 16th, 2020, so save the date, I guess! 

If you want to track the progress of the blog integration, along with sneak peeks into development, you can follow [this pull request on 30-seconds-web](https://github.com/30-seconds/30-seconds-web/pull/33).

**Comment by anshuraj** [comment]
Can anyone write blog here?

**Comment by Chalarangelo** [comment]
@anshuraj Right now, we don't even have proper guidelines and procedures for this. However, if you are interested, we will create guidelines in the following months, which will allow community members to contribute to the blog.
